WebApplication-Test/Models/Model-Test.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication_Test.Models
{
    public class Model_Test
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public int Dni { get; set; }

    }
}

WebApplication-Test/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication_Test.Models;
using WebApplication_Test.Modules;

namespace WebApplication_Test.Controllers
{
    public class AjaxController : Controller
    {
        private readonly ModulesDb modules = new ModulesDb();
        // GET: Ajax
        public ActionResult Index(Model_Test model)
        {
            
            return View(model);
        }

        [HttpPost]
        public JsonResult GetUser(Model_Test model)
        {

                if (model.Name != null && model.LastName != null)
                {
                    List<SqlParameter> parameters = new List<SqlParameter>();
                    parameters.Add(modules.ParameterString("@name", model.Name));
                    parameters.Add(modules.ParameterString("@lastname", model.LastName));

                    var res = modules.UserGet
                        (
                        "Select * from [dbo].[Users] where @name = Name AND @lastname = LastName"
                        ,parameters
                        );
                    if(res.Id <= 0)
                    {
                        return Json(false);
                    }
                    return Json(res);
                }
                else
                {

                    return Json(false);
                }

           

        }
        public ActionResult ListUser()
        {
            List<Model_Test> petition;
            try
            {
                petition = modules.ListUserGet("Select * from [dbo].[Users]");
                
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Error: " + ex.Message;
                return View();
            }
            return View(petition);
        }
    }
}

WebApplication-Test/Views/Ajax/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>Consulta</h2>
    <div style="margin:15px 0px 0px 0px">
        <input id="name" class="form-control" type="text" placeholder="Nombre" />
    </div>

    <div style="margin:15px 0px 15px 0px">
        <input id="lastName" class="form-control" type="text" placeholder="Apellido" />

    </div>
    <div>
        <button type="submit" id="btn-send" class="btn-primary">Enviar</button>

    </div>

</div>

<div id="result">

</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#btn-send").click(function () {
                $.ajax({
                    url: '@Url.Action("GetUser","Ajax")',
                    type: 'POST',
                    data: {
                        Name: $("#name").val(),
                        LastName: $("#lastName").val()
                    },
                    dataType: 'json',
                    success: function (data) {
                        
                        if (data != false) {
                            var result = "";
                            localStorage.setItem("User", JSON.stringify(data));
                            console.log(data);

                            result += `
                                    </br><p><b>Nombre:</b> ${data.Name}</p>
                                    </br><p><b>Apellido:</b> ${data.LastName}</p>
                                    </br><p><b>Edad:</b> ${data.Age}</p>
                                    </br><p><b>DNI:</b> ${data.Dni}</p>
                                        `
                          

                            document.getElementById("result").innerHTML = result;

                        } else {
                            alert('Los registros no coinciden con los datos ingresados o no existen')
                        }
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        alert(" " + errorThrown + " " + "Status: "+JSON.stringify(xhr.status));
                    }
                    

                })
            })
        })
    </script>
    }

WebApplication-Test/Views/Ajax/ListUser.cshtml
@model  List<WebApplication_Test.Models.Model_Test>
@{
    ViewBag.Title = "ListUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de usuarios</h2>


@if (Model != null)
{
    <div class="row">
        <div class="col-xs-1 table-bordered text-center"><b>ID</b></div>
        <div class="col-xs-1 table-bordered text-center"><b>NOMBRE</b></div>
        <div class="col-xs-1 table-bordered text-center"><b>APELLIDO</b></div>
        <div class="col-xs-1 table-bordered text-center"><b>EDAD</b></div>
        <div class="col-xs-1 table-bordered text-center"><b>DNI</b></div>
    </div>

    foreach (var items in Model)
    {
        <div class="row ">

            <div class="col-xs-1 table-bordered text-center">@items.Id</div>
            <div class="col-xs-1 table-bordered text-center">@items.Name</div>
            <div class="col-xs-1 table-bordered text-center">@items.LastName</div>
            <div class="col-xs-1 table-bordered text-center">@items.Age</div>
            <div class="col-xs-1 table-bordered text-center">@items.Dni</div>

        </div>
    }

}
else
{
    if (ViewBag.Message != null)
    {
        <h1 class="text-danger">@ViewBag.Message</h1>
    }
    else
    {
        <h1 class="text-danger">@ViewBag.Error</h1>
    }
}

WebApplication-Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test Aplicacion", "Index", "Ajax", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Consulta", "Index", "Ajax")</li>
                    <li>@Html.ActionLink("Lista de usuarios", "ListUser", "Ajax")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>